# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "mode=0755"
    ];
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5bf75352-a227-4f9d-90f8-741088d75b21";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/5bf75352-a227-4f9d-90f8-741088d75b21";
      fsType = "btrfs";
      options = [ "subvol=nixos-config" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/5bf75352-a227-4f9d-90f8-741088d75b21";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/5bf75352-a227-4f9d-90f8-741088d75b21";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5bf75352-a227-4f9d-90f8-741088d75b21";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CE5-DAE3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a64e0951-3084-47d2-996e-56f496714295"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
